### ISSUE TITLE
[버그] #5 기지내부 중앙방에서 몬스터 다시 보이는 현상

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/MC_contents5#12]
- 중앙방에서 드론을 모두 잡고 이벤트 후 오른쪽 맵으로 이동시 드론이 다시 리젠되었다가 사라지는 현상
![녹화_2020_02_12_09_58_08_254 mp4_20200212_105820 564](https://user-images.githubusercontent.com/15261449/74296179-77421f80-4d86-11ea-91c6-b334104ceb31.jpg)

**Comment by Yangsiyoung0901** [comment]
해결 완료했습니다
