### ISSUE TITLE
[버그]#9_보스방  

### ISSUE THREAD

**Issue by lee1030cjs** [kyungho-lee/MC_contents5#15]
![image](https://user-images.githubusercontent.com/58832533/74317986-b2147980-4dbf-11ea-80c4-ef48e7bf5019.png)

#9보스방에서 모든 대사처리 후 스페이스바 연속터치 시  #9-1보스방 1페이즈로 이동 이후
무적판정과 이동불가가 된다.

+ 
맵이동시 페이드효과를 넣으면 문제 없음

**Comment by Yangsiyoung0901** [comment]
해결완료~~
