### ISSUE TITLE
[개선 사항] 그래픽

### ISSUE THREAD

**Issue by CheonSehyeon** [kyungho-lee/MC_contents5#16]
- [x] 1. 월드맵에 미니맵 그래픽 수정(던전 표기 X)
- [ ] 2. Ingame Screen에 [PRESS SPACE] 버튼만 표기
- [x] 3. 스킬 아이콘 애니메이션 수정(스킬 아이콘 -> PRESS BUTTON(Z or X) -> 스킬 아이콘)
- [x] 4. 맵마다 Background 및 UI 타일로 배치
- [x] 5. 전체 맵 그래픽 수정

**Comment by kyungho-lee** [comment]
2번은 제외합니다.
