### ISSUE TITLE
[개선사항] 모듈획득시 메시지 처리

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/MC_contents5#17]
- 모듈획득시 메시지창 처리

필요조건 )
1. 메시지 출력으로 캐릭터 이동에 방해가 되지 않아야 한다.
2. 전투시 캐릭터 이동에 방해가 되지 않는 위치에 배치 필요
3. 모듈장착을 하거나 무기를 변경할때는 외부공격을 받지 않는 안전지대로 설정할 필요가 있다.
   - 단 의도적으로 연출할때는 예외로한다.

**Comment by Yangsiyoung0901** [comment]
이미지를 띄워주는 형태로 캐릭터 움직임 제약없이 모듈 스왑이 가능하게 기능 구현을 완료하였습니다.

**Comment by kyungho-lee** [comment]
# resource
- 모듈획득 정보 이미지 구성
   Equip  아이콘 /모듈이름 / 


# display @CheonSehyeon 
- 무기
![image](https://user-images.githubusercontent.com/15261449/74400551-96fa4600-4e61-11ea-9354-6aa1b8d69c43.png)
- 모듈
![image](https://user-images.githubusercontent.com/15261449/74400575-a8dbe900-4e61-11ea-8ea3-29e0f3517205.png)
