### ISSUE TITLE
[개선사항] 그래픽 리소스 추가 요청

### ISSUE THREAD

**Issue by Yangsiyoung0901** [kyungho-lee/MC_contents5#18]
1. 보스 몬스터 사망 그래픽 리소스
파괴 된 보스 Idle 모션이 필요

2. 보스 2 페이즈에서 레이저 건
비활성 상태와 활성 상태의 대형 레이저 건 그래픽 리소스
또한, 드론을 잡을 때 마다 10%씩 충전되는 문자형 리소스도 필요

3. 폭발형 몬스터
현재 좀비 >> 다리달린 폭탄?

4. 초록색 드론의 사망 이미지

**Comment by lee1030cjs** [comment]
3번요청사항은 내부에 적용된 다른 리소스적용 후 
사운드와 이펙트효과를 더해 폭발형 몬스터로 연출하는 것으로 수정되었습니다.

**Comment by kyungho-lee** [comment]
포발형 몬스터는 검은색 드론으로 대체?
