### ISSUE TITLE
콘텐츠 및 연출 작업 

### ISSUE THREAD

**Issue by Kohemi** [kyungho-lee/MC_contents5#23]
### 대사 작업
- [x] 연구실 내부
- [x] 기지입구 
- [x] 기지내부
- [x] 기지내부 반사체
- [x] 기지내부 중앙방
- [x] 폰트 및 크기 조정 
- [x] 보스방

### BGM 작업 
- [x] 침실 사이렌 소리, 워프 소리

### 엔딩부 및 기타 연출 작업 
* 한 번에 넘어가지 않게끔 대사 중간 연출 삽입 필요

- [x] 크레딧 작업 필요
- [x] 타이틀 화면 수정 필요  
- [x] _GameOver 화면 필요_

**Comment by kyungho-lee** [comment]
@Kohemi 님 보스캐릭터 리터칭 작업을 최우선으로 합니다.
- 나머지 대사 작업 및 연출부분은 저와 함께 작업합니다.

**Comment by kyungho-lee** [comment]
마지막 쿠키영상 이후 텍스트 추가 "꿈은 결과없이 죄를 저지를수 있는 안식처이다". 
휠체어에 타고 있는 노인이 VR을 쓴채 미소를 지으며 죽음을 맞이 한다.
