### ISSUE TITLE
[bug alpha ver 0.2] 크리스탈퍼즐 ESC 버튼작동

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/MC_contents5#39]
# 오류상태
- 크리스탈 워프퍼즐맵에서 ESC키가 작동되는 현상

![image](https://user-images.githubusercontent.com/15261449/74589343-d97d7780-5047-11ea-8207-344b9e9687c9.png)

ESC 토글이 안되어 복귀할 수 없다. (앱을 종료해야함)

**Comment by kyungho-lee** [comment]
- 이후 게임재시작후 타이틀에서 x 버튼을 누르면 팝업이 나옴

![image](https://user-images.githubusercontent.com/15261449/74589999-cb325a00-504d-11ea-800a-9eb017fa3a65.png)

**Comment by Yangsiyoung0901** [comment]
수정 완료했습니다.
