### ISSUE TITLE
[개선사항] 카드키를 주는 스테이지 개선

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/MC_contents5#41]
# 개선사항
- 카드키를 주는 스테이지에서 드론 몬스터의 이동 부분을 캐릭터와 간격을 변경해서 난이도를 조정합니다. 플레이어를 초반부터 보고 공격하지 않고 로밍중에 발견해서 이동하게끔해서 초반에 죽는 경험을 최소화 합니다.
- 카드키 드론의 색상을 변경해서 구분시켜줍니다.

**Comment by lee1030cjs** [comment]
1. 7,9   8,9좌표를 지날 시 몬스터가 캐릭터를 발견하고 공격과 이동을 시작하도록 수정함
2. 드론색상 변경완료.
