### ISSUE TITLE
[버그 alpha ver 0.3] 리플렉션쉴드 퍼즐후 이동시 

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/MC_contents5#45]
## 오류상황 
- 리플렉션 쉴드로 반사해서 처치하는 스테이지 이전에 드론을 잡지않고 가는 경우
- 스테이지 클리어 후 되돌아 왔을때 대사중 드론이 공격을 해서 진행할 수 없는 현상

## 수정방안
1. 이전 스테이지 (드론 3기)를 모두 잡고 이동하는 방법 (왼쪽에 문을 설치해서 열기위해 모두 잡는다.)
2. 왼쪽 통로 주변에 안전지대를 설치한다.
3. 대사중에는 드론3기가 공격하지 않는다.

**Comment by lee1030cjs** [comment]
'3.대사중에는 드론 3기가 공격하지 않는다.'로 수정 완료
