### ISSUE TITLE
[LevelDesign] PlayTime 설계

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/MC_contents5#9]
# focus
- 플레이 이동동선
- 맵 별 이벤트 설계
- 맵 별 시나리오 및 텍스트 이벤트
- 레벨 밸런스 기준 
    1. 타임라인 진행에 따라 점점 어려워 지는 단계를 느낄수 있게 한다.

**Comment by kyungho-lee** [comment]
@lee1030cjs 님 클로즈 베타는 #7번 기지지하에서 분기는 없애고 폭발이후 물길미로로 진행합니다.

**Comment by lee1030cjs** [comment]
완료되었습니다.
